In [5]:
import numpy as np
from scipy.signal import savgol_filter

dumdict = {'tuvieja': 6, 'tumami': 7}

In [6]:
try:
    tm = dumdict[tumama]
except NameError:
    tm = 0
    
tm

0

In [26]:
a = np.stack([np.arange(1500)* (i+1) for i in range(3)])
a

array([[   0,    1,    2, ..., 1497, 1498, 1499],
       [   0,    2,    4, ..., 2994, 2996, 2998],
       [   0,    3,    6, ..., 4491, 4494, 4497]])

In [25]:
a[:, ::3].shape

array([[   0,    0,    0, ...,    0,    0,    0],
       [   0,    3,    6, ..., 1491, 1494, 1497],
       [   0,    6,   12, ..., 2982, 2988, 2994]])

In [29]:
b = np.stack([np.convolve(x, np.ones(3), mode='same')/3 for x in a]).astype(np.int)
b

array([[   0,    1,    2, ..., 1497, 1498,  999],
       [   0,    2,    4, ..., 2994, 2996, 1998],
       [   1,    3,    6, ..., 4491, 4494, 2997]])

In [30]:
c = np.stack([np.convolve(x, np.ones(3), mode='same')/3 for x in a])[:, ::3].astype(np.int)
c

array([[   0,    3,    6, ..., 1491, 1494, 1497],
       [   0,    6,   12, ..., 2982, 2988, 2994],
       [   1,    9,   18, ..., 4473, 4482, 4491]])

In [ ]:
from scipy.signal import savgol_filter

c = savgol_filter(a[0], 5, 2)
c

In [1]:
c

NameError: name 'c' is not defined